image: teracy/angular-cli

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - ng b --env=prod
    - firebase use devoxx2018-pwa production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY 